### ISSUE TITLE
Create instructive readme?

### ISSUE THREAD

**Issue by spacey-sooty** [Superbro525Alt/Hollowpoint#1]
I think this would greatly benefit from an instructive readme but I tried it out and it was fire 🔥

**Comment by Superbro525Alt** [comment]
Ok

**Comment by spacey-sooty** [comment]
based but what abt instructions for how to play the game? maybe add a page in the game?

**Comment by Superbro525Alt** [comment]
Is that better?

Thanks for the suggestion!

**Comment by spacey-sooty** [comment]
Beautiful thank you 🔥
